services:
  - type: web
    name: trip-recommender
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "import nltk; nltk.download('punkt')"
    startCommand: gunicorn main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.9