services:
  - type: web
    name: trip-recommender
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120 --workers 1 --threads 2
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTORCH_CUDA_ALLOC_CONF
        value: "max_split_size_mb:128"